// <auto-generated />
#nullable enable

namespace FbSample.Views;

partial class AboutControl
{
    private System.ComponentModel.IContainer? components = null;

    /// <inheritdoc />
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        SuspendLayout();
        //
        // AboutControl
        //
        AutoScaleMode = AutoScaleMode.Inherit;
        BackColor = Color.White;
        Name = "AboutControl";
        Size = new Size(598, 396);
        ResumeLayout(false);
    }
}
