<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>FbSample</RootNamespace>
    <AssemblyName>FbSample</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationDefaultFont>Microsoft YaHei UI, 10pt</ApplicationDefaultFont>
    <ApplicationIcon>Resources/App.ico</ApplicationIcon>
    <NeutralLanguage>en-US</NeutralLanguage>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AntdUI" />
    <InternalsVisibleTo Include="FbSample.Tests" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties/Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Properties/Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Views/MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views/Pages/SettingsPage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views/AboutControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views/Controls/NavigationFlyoutControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="../../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
